# Python 1 - Introduction to Python


## Objectives

* Get used to the IPython Notebook.
* Understand what a library is and how to use it.
* Read tabular data from a file into a program.
* Assign values to variables.
* Select individual values and subsections from data.
* Perform operations on arrays of data.
* Display simple graphs.



## IPython Notebook

IPython notebook is a web based interactive computational environment with code, text, mathematics, plot and exectution all in the same place. Its how we'll be doing the whole course, though we wouldn't use it for more script based programming, for that we suggest you use Spyder or your pet text editor.

A few shortcuts to make your life easier:

- crtl + enter - Run the contents of this cell
- B - insert cell below this one when whole cell is selected
- esc - moves from this window to select the whole box
- enter - will move you back in
- M - changes the whole box to markdown
- Y - changes the whole box to code

## Libraries

Words are useful, but what’s more useful are the sentences and stories we build with them. Similarly, while a lot of powerful tools are built into languages like Python, even more live in the libraries they are used to build.

Numpy is one of the essential libraries we use in python. We can import it thusly:

In [4]:
import numpy

We're going to demonstrate how to use the NumPy library with some data on patient inflammmation info. We can import cvs file as so:

In [6]:
afile = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

So lets examine this. By typing `numpy.loadtxt()` we're saying, from the numpy library use the loadtxt function. Its the equivalent of selecting a file from a directory, or saying thing.component.

`loadtxt()` is a function call, which in this case has two arguments passed to it. The filename and the delimiter, both need to be input as character strings.

### Strings

Character strings are sequences of characters enclosed in either `""` or `''`. We typically use these in keyword argument calls to function, as above, and output to the console, more of which later.

Now if we type the variable the file is attached to into the interpreter, we see the data held within it as an array, with the delimiter `,` seperating all the values.


In [7]:
afile

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

### Variables

The fact that this array is saved to a variable means that the array is stored in the computers memory. Variables are an essential part of programming. Lets look at them in more detail. We can assign values to variables


In [18]:
temp = 34

Modify them

In [19]:
temp + 2.2

36.2

Reassign them

In [27]:
temp= 37

Do some schmancy printing with them, throwing in a bit of string usage too

In [21]:
print "The temperature of this spam is", temp, "please take it back"

The temperature of this spam is 37 please take it back


We can also use variables to define other variables

In [28]:
temp_K = temp + 273
temp_K

310

and then we can change the temperature in Kelvin

In [29]:
temp_K = temp_K + 10
temp_K


320

Note that changing the temperature in Kelvin does not change the previous temperature we used to calculate it in the first place

In [30]:
temp

37

<section class="objectives panel panel-warning">
<div class="panel-heading">
<h2><span class="fa fa-certificate"></span> Tip </h2>
</div>
You can use the `%whos` command at any time to see what variables you have created and what modules you have loaded into the computers memory. As this is an IPython command, it will only work if you are in an IPython terminal or the Jupyter Notebook.
</section>

In [32]:
%whos

Variable      Type       Data/Info
----------------------------------
afile         ndarray    60x40: 2400 elems, type `float64`, 19200 bytes
numpy         module     <module 'numpy' from '/us<...>ages/numpy/__init__.pyc'>
temp          int        37
temp_K        int        320
temperature   int        37
temperture    int        37


Now back to the patients. We have the patient infomation sorted in memory as the variable `afile`, and we can check its still there with `type`, lets find out more about the array.

In [34]:
print type(afile)
print afile.shape

<type 'numpy.ndarray'>
(60, 40)


These two commands tell us that the variable is an NumPy ndarray and then the extent of the array. In this case the rows are individual patients and the columns are their daily inflammation measurements. In this case we have 60 rows and 40 columns, known as the attributes of the array. Using these attributes we can index the data to extract single data values:

In [37]:
print afile[12,15]
print afile[0,0]

12.0
0.0


<section class="objectives panel panel-warning">
<div class="panel-heading">
<h2><span class="fa fa-certificate"></span> Indexing </h2>
</div>

What may also surprise you is that when Python displays an array, it shows the element with index [0, 0] in the upper left corner rather than the lower left. This is consistent with the way mathematicians draw matrices, but different from the Cartesian coordinates. The indices are (row, column) instead of (column, row) for the same reason, which can be confusing when plotting data.

</section>

We can also index a specific row or column. This can my done by using a colon in our call:

In [38]:
afile[:,15]

array([  4.,   4.,  15.,   8.,  10.,  15.,  13.,   9.,  11.,   6.,   3.,
         8.,  12.,   3.,   5.,  10.,  11.,   4.,  11.,  13.,  15.,   5.,
        14.,  13.,   4.,   9.,  13.,   6.,   7.,   6.,  14.,   3.,  15.,
         4.,  15.,  11.,   7.,  10.,  15.,   6.,   5.,   6.,  15.,  11.,
        15.,   6.,  11.,  15.,  14.,   4.,  10.,  15.,  11.,   6.,  13.,
         8.,   4.,  13.,  12.,   9.])

In [39]:
afile[15,:]

array([  0.,   1.,   1.,   0.,   1.,   2.,   4.,   3.,   6.,   4.,   7.,
         5.,   5.,   7.,   5.,  10.,   7.,   8.,  18.,  17.,   9.,   8.,
        12.,  11.,  11.,  11.,  14.,   6.,  11.,   2.,  10.,   9.,   5.,
         6.,   5.,   3.,   4.,   2.,   2.,   0.])